# Generated by Django 6.0 on 2026-02-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='players',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='trainings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='trainings_tasks',
                to='tasks.task',
            ),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='training',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='trainings_tasks',
                to='trainings.training',
            ),
        ),
        migrations.AddField(
            model_name='training',
            name='tasks',
            field=models.ManyToManyField(
                related_name='trainings',
                through='trainings.TrainingTask',
                to='tasks.task',
            ),
        ),
        migrations.AddIndex(
            model_name='trainingtask',
            index=models.Index(
                fields=['training'], name='trainings_t_trainin_614670_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='trainingtask',
            index=models.Index(fields=['task'], name='trainings_t_task_id_a7f910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingtask',
            unique_together={('training', 'order')},
        ),
    ]
