# Generated by Django 6.0 on 2026-02-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='players',
            new_name='player',
        ),
    ]
