# Generated by Django 6.0 on 2026-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_rename_players_training_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('technical_error', 'Technical error')], default='in_progress', max_length=20),
        ),
    ]
