server {
  listen 3000;

  location = /index.html {
    root /usr/share/nginx/html;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    expires off;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;

    if ($request_uri ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$) {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
  }

  include /etc/nginx/extra-conf.d/*.conf;
}
