networks:
  pr:
  my_proxy_network:
    external: true

services:
  frontend-pr:
    build:
      context: ./frontend
    container_name: frontend-pr
    networks:
      - pr

  nginx-pr:
    container_name: nginx-pr
    restart: always
    image: nginx:stable-alpine
    expose:
      - "80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './static:/usr/share/nginx/html/static'
    depends_on:
      - django-pr
      - frontend-pr
    networks:
      - pr
      - my_proxy_network

  pg-pr:
    image: postgres:16-alpine
    container_name: pg-pr
    environment:
      POSTGRES_DB: olympiad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pr

  redis-ch-pr:
    image: redis:7-alpine
    container_name: redis-ch-pr
    networks:
      - pr

  redis-ca-pr:
    image: redis:7-alpine
    container_name: redis-ca-pr
    networks:
      - pr

  django-pr:
    build:
      context: ./backend
    container_name: django-pr
    environment:
      DJANGO_SETTINGS_MODULE: olympiad.settings
      DB_HOST: pg-pr
      DB_PORT: 5432
      DB_NAME: olympiad
      DB_USER: postgres
      DB_PASSWORD: root
      REDIS_CHANNEL_HOST: redis-ch-pr
      REDIS_CACHE_HOST: redis-ca-pr
    depends_on:
      pg-pr:
        condition: service_healthy
      redis-ch-pr:
        condition: service_started
      redis-ca-pr:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - static_files:/app/staticfiles
      - ./backend/dump.json:/app/dump.json
    networks:
      - pr

volumes:
  pg_data:
  static_files: