# Generated by Django 6.0 on 2026-02-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTheme',
            new_name='SubjectTheme',
        ),
    ]
