# Generated by Django 6.0 on 2026-02-19 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasktheme_subjecttheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tasks',
                to='tasks.subjecttheme',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(
                choices=[
                    ('easy', 'Лёгкий'),
                    ('middle', 'Средний'),
                    ('high', 'Сложный'),
                ],
                default=1,
                max_length=20,
            ),
        ),
    ]
