# Generated by Django 6.0 on 2026-03-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_theme_alter_task_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='source',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TaskSource',
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
    ]
