# Generated by Django 6.0 on 2026-03-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_source_remove_task_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='solution',
        ),
    ]
