# Generated by Django 6.0 on 2026-04-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
