# Generated by Django 6.0 on 2026-04-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='solution',
        ),
    ]
