# Generated by Django 6.0 on 2026-02-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_of_attempts', models.PositiveIntegerField(default=1)),
                ('user_answer', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_to_solve', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_statistics',
            },
        ),
        migrations.CreateModel(
            name='RoundStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_of_attempts', models.PositiveIntegerField(default=1)),
                ('user_answer', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_to_solve', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'round_task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='round_statistics',
                        to='pvp.roundtask',
                    ),
                ),
            ],
            options={
                'db_table': 'round_statistics',
            },
        ),
    ]
