# Generated by Django 6.0 on 2026-02-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0002_initial'),
        ('user_statistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roundstatistics',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='round_statistics',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='trainingstatistics',
            name='training_task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='statistics',
                to='trainings.trainingtask',
            ),
        ),
        migrations.AddField(
            model_name='trainingstatistics',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='training_statistics',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='roundstatistics',
            index=models.Index(fields=['user'], name='round_stati_user_id_166b63_idx'),
        ),
        migrations.AddIndex(
            model_name='roundstatistics',
            index=models.Index(
                fields=['round_task'], name='round_stati_round_t_869990_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='roundstatistics',
            index=models.Index(
                fields=['is_correct'], name='round_stati_is_corr_15eae4_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='roundstatistics',
            unique_together={('user', 'round_task')},
        ),
        migrations.AddIndex(
            model_name='trainingstatistics',
            index=models.Index(fields=['user'], name='training_st_user_id_5dc907_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingstatistics',
            index=models.Index(
                fields=['training_task'], name='training_st_trainin_2385a7_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='trainingstatistics',
            index=models.Index(
                fields=['is_correct'], name='training_st_is_corr_1f254c_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='trainingstatistics',
            unique_together={('user', 'training_task')},
        ),
    ]
