# Generated by Django 6.0 on 2026-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasktheme_subjecttheme'),
        ('users', '0002_usertask_user_solved_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved_tasks',
            field=models.ManyToManyField(
                related_name='solved_tasks', through='users.UserTask', to='tasks.task'
            ),
        ),
    ]
